// DTO => Data Transfer Object

class IssuedBook{
    _id; // Auto-generated by mongoDB
    name;
    genre;
    price;
    publisher;
    issuedBy;
    issuedDate;
    returnDate;
    
    constructor(user){
        this._id = user.IssuedBook._id;
        this.name = user.IssuedBook.name;
        this.genre = user.IssuedBook.genre;
        this.price = user.IssuedBook.price;
        this.publisher = user.IssuedBook.publisher;
        this.issuedBy = user.IssuedBook.issuedBy;
        this.issuedDate = user.IssuedBook.issuedDate;
        this.returnDate = user.IssuedBook.returnDate;
    }
}


module.exports = IssuedBook;